# breast-level training, sigmoid-windowing is not applied
VER: '084'
INPUT_BASE: 'data/input'
OUTPUT_BASE: 'data/output'
DEVICE: 'cuda:0'
SIZE: [1520, 912]
MEAN: 0.3089279
STD: 0.25053555408335154
level: breast
external: false
windowing: false
seed: 10
batch_size: 8
lr: 5.0e-5
n_folds: 4
epochs: 10
epochs_warmup: 0
num_cycles: 0.5
apex: true
print_freq: 100
name: 'tf_efficientnet_b5_ns'
# parameters for elastic deformation
a: 10
s: 15
